import type { Image, Favourite } from "@api/types";

export const catImages: Image[] = [
  {
    breeds: [],
    categories: [
      {
        id: 9,
        name: "dream",
      },
    ],
    id: "6gc",
    url: "https://cdn2.thecatapi.com/images/6gc.jpg",
    width: 500,
    height: 333,
  },
  {
    breeds: [],
    id: "auo",
    url: "https://cdn2.thecatapi.com/images/auo.jpg",
    width: 480,
    height: 360,
  },
  {
    breeds: [],
    id: "bit",
    url: "https://cdn2.thecatapi.com/images/bit.jpg",
    width: 500,
    height: 333,
  },
  {
    breeds: [],
    id: "c0d",
    url: "https://cdn2.thecatapi.com/images/c0d.jpg",
    width: 493,
    height: 700,
  },
  {
    breeds: [],
    id: "d7s",
    url: "https://cdn2.thecatapi.com/images/d7s.jpg",
    width: 324,
    height: 394,
  },
  {
    breeds: [],
    id: "dmo",
    url: "https://cdn2.thecatapi.com/images/dmo.jpg",
    width: 640,
    height: 480,
  },
  {
    breeds: [],
    id: "MTY0NjU4Mg",
    url: "https://cdn2.thecatapi.com/images/MTY0NjU4Mg.jpg",
    width: 1600,
    height: 1200,
  },
  {
    breeds: [],
    id: "MTk0Njc0MQ",
    url: "https://cdn2.thecatapi.com/images/MTk0Njc0MQ.jpg",
    width: 533,
    height: 800,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "5 - 10",
          metric: "2 - 5",
        },
        id: "orie",
        name: "Oriental",
        cfa_url: "http://cfa.org/Breeds/BreedsKthruR/Oriental.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/oriental",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/oriental",
        temperament:
          "Energetic, Affectionate, Intelligent, Social, Playful, Curious",
        origin: "United States",
        country_codes: "US",
        country_code: "US",
        description:
          "Orientals are passionate about the people in their lives. They become extremely attached to their humans, so be prepared for a lifetime commitment. When you are not available to entertain her, an Oriental will divert herself by jumping on top of the refrigerator, opening drawers, seeking out new hideaways.",
        life_span: "12 - 14",
        indoor: 0,
        lap: 1,
        alt_names: "Foreign Type",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 1,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 3,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Oriental_Shorthair",
        hypoallergenic: 1,
        reference_image_id: "LutjkZJpH",
      },
    ],
    id: "0eVXT8_lb",
    url: "https://cdn2.thecatapi.com/images/0eVXT8_lb.jpg",
    width: 1396,
    height: 1080,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "7 - 14",
          metric: "3 - 6",
        },
        id: "ebur",
        name: "European Burmese",
        cfa_url: "http://cfa.org/Breeds/BreedsCJ/EuropeanBurmese.aspx",
        temperament: "Sweet, Affectionate, Loyal",
        origin: "Burma",
        country_codes: "MM",
        country_code: "MM",
        description:
          "The European Burmese is a very affectionate, intelligent, and loyal cat. They thrive on companionship and will want to be with you, participating in everything you do. While they might pick a favorite family member, chances are that they will interact with everyone in the home, as well as any visitors that come to call. They are inquisitive and playful, even as adults. ",
        life_span: "10 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        cat_friendly: 4,
        dog_friendly: 4,
        energy_level: 4,
        grooming: 1,
        health_issues: 4,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 4,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        hypoallergenic: 0,
      },
    ],
    id: "oLtx9gsxx",
    url: "https://cdn2.thecatapi.com/images/oLtx9gsxx.jpg",
    width: 4027,
    height: 2680,
  },
];

export const catImagesBirmanBreed: Image[] = [
  {
    breeds: [
      {
        weight: {
          imperial: "6 - 15",
          metric: "3 - 7",
        },
        id: "birm",
        name: "Birman",
        cfa_url: "http://cfa.org/Breeds/BreedsAB/Birman.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/birman",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/birman",
        temperament: "Affectionate, Active, Gentle, Social",
        origin: "France",
        country_codes: "FR",
        country_code: "FR",
        description:
          "The Birman is a docile, quiet cat who loves people and will follow them from room to room. Expect the Birman to want to be involved in what you’re doing. He communicates in a soft voice, mainly to remind you that perhaps it’s time for dinner or maybe for a nice cuddle on the sofa. He enjoys being held and will relax in your arms like a furry baby.",
        life_span: "14 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "Sacred Birman, Sacred Cat Of Burma",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 2,
        health_issues: 1,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 4,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Birman",
        hypoallergenic: 0,
        reference_image_id: "HOrX5gwLS",
      },
    ],
    id: "OhTkBTPnD",
    url: "https://cdn2.thecatapi.com/images/OhTkBTPnD.jpg",
    width: 1100,
    height: 1100,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "6 - 15",
          metric: "3 - 7",
        },
        id: "birm",
        name: "Birman",
        cfa_url: "http://cfa.org/Breeds/BreedsAB/Birman.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/birman",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/birman",
        temperament: "Affectionate, Active, Gentle, Social",
        origin: "France",
        country_codes: "FR",
        country_code: "FR",
        description:
          "The Birman is a docile, quiet cat who loves people and will follow them from room to room. Expect the Birman to want to be involved in what you’re doing. He communicates in a soft voice, mainly to remind you that perhaps it’s time for dinner or maybe for a nice cuddle on the sofa. He enjoys being held and will relax in your arms like a furry baby.",
        life_span: "14 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "Sacred Birman, Sacred Cat Of Burma",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 2,
        health_issues: 1,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 4,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Birman",
        hypoallergenic: 0,
        reference_image_id: "HOrX5gwLS",
      },
    ],
    id: "Dm0H1zSK1",
    url: "https://cdn2.thecatapi.com/images/Dm0H1zSK1.jpg",
    width: 1024,
    height: 768,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "6 - 15",
          metric: "3 - 7",
        },
        id: "birm",
        name: "Birman",
        cfa_url: "http://cfa.org/Breeds/BreedsAB/Birman.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/birman",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/birman",
        temperament: "Affectionate, Active, Gentle, Social",
        origin: "France",
        country_codes: "FR",
        country_code: "FR",
        description:
          "The Birman is a docile, quiet cat who loves people and will follow them from room to room. Expect the Birman to want to be involved in what you’re doing. He communicates in a soft voice, mainly to remind you that perhaps it’s time for dinner or maybe for a nice cuddle on the sofa. He enjoys being held and will relax in your arms like a furry baby.",
        life_span: "14 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "Sacred Birman, Sacred Cat Of Burma",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 2,
        health_issues: 1,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 4,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Birman",
        hypoallergenic: 0,
        reference_image_id: "HOrX5gwLS",
      },
    ],
    id: "xRMeDCybn",
    url: "https://cdn2.thecatapi.com/images/xRMeDCybn.jpg",
    width: 1068,
    height: 1068,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "6 - 15",
          metric: "3 - 7",
        },
        id: "birm",
        name: "Birman",
        cfa_url: "http://cfa.org/Breeds/BreedsAB/Birman.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/birman",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/birman",
        temperament: "Affectionate, Active, Gentle, Social",
        origin: "France",
        country_codes: "FR",
        country_code: "FR",
        description:
          "The Birman is a docile, quiet cat who loves people and will follow them from room to room. Expect the Birman to want to be involved in what you’re doing. He communicates in a soft voice, mainly to remind you that perhaps it’s time for dinner or maybe for a nice cuddle on the sofa. He enjoys being held and will relax in your arms like a furry baby.",
        life_span: "14 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "Sacred Birman, Sacred Cat Of Burma",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 2,
        health_issues: 1,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 4,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Birman",
        hypoallergenic: 0,
        reference_image_id: "HOrX5gwLS",
      },
    ],
    id: "3rK7HGo7r",
    url: "https://cdn2.thecatapi.com/images/3rK7HGo7r.jpg",
    width: 1024,
    height: 1536,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "6 - 15",
          metric: "3 - 7",
        },
        id: "birm",
        name: "Birman",
        cfa_url: "http://cfa.org/Breeds/BreedsAB/Birman.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/birman",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/birman",
        temperament: "Affectionate, Active, Gentle, Social",
        origin: "France",
        country_codes: "FR",
        country_code: "FR",
        description:
          "The Birman is a docile, quiet cat who loves people and will follow them from room to room. Expect the Birman to want to be involved in what you’re doing. He communicates in a soft voice, mainly to remind you that perhaps it’s time for dinner or maybe for a nice cuddle on the sofa. He enjoys being held and will relax in your arms like a furry baby.",
        life_span: "14 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "Sacred Birman, Sacred Cat Of Burma",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 2,
        health_issues: 1,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 4,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Birman",
        hypoallergenic: 0,
        reference_image_id: "HOrX5gwLS",
      },
    ],
    id: "2LEN_GHmx",
    url: "https://cdn2.thecatapi.com/images/2LEN_GHmx.jpg",
    width: 1600,
    height: 1200,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "6 - 15",
          metric: "3 - 7",
        },
        id: "birm",
        name: "Birman",
        cfa_url: "http://cfa.org/Breeds/BreedsAB/Birman.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/birman",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/birman",
        temperament: "Affectionate, Active, Gentle, Social",
        origin: "France",
        country_codes: "FR",
        country_code: "FR",
        description:
          "The Birman is a docile, quiet cat who loves people and will follow them from room to room. Expect the Birman to want to be involved in what you’re doing. He communicates in a soft voice, mainly to remind you that perhaps it’s time for dinner or maybe for a nice cuddle on the sofa. He enjoys being held and will relax in your arms like a furry baby.",
        life_span: "14 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "Sacred Birman, Sacred Cat Of Burma",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 2,
        health_issues: 1,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 4,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Birman",
        hypoallergenic: 0,
        reference_image_id: "HOrX5gwLS",
      },
    ],
    id: "C0BNiXO0T",
    url: "https://cdn2.thecatapi.com/images/C0BNiXO0T.jpg",
    width: 1526,
    height: 2111,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "6 - 15",
          metric: "3 - 7",
        },
        id: "birm",
        name: "Birman",
        cfa_url: "http://cfa.org/Breeds/BreedsAB/Birman.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/birman",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/birman",
        temperament: "Affectionate, Active, Gentle, Social",
        origin: "France",
        country_codes: "FR",
        country_code: "FR",
        description:
          "The Birman is a docile, quiet cat who loves people and will follow them from room to room. Expect the Birman to want to be involved in what you’re doing. He communicates in a soft voice, mainly to remind you that perhaps it’s time for dinner or maybe for a nice cuddle on the sofa. He enjoys being held and will relax in your arms like a furry baby.",
        life_span: "14 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "Sacred Birman, Sacred Cat Of Burma",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 2,
        health_issues: 1,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 4,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Birman",
        hypoallergenic: 0,
        reference_image_id: "HOrX5gwLS",
      },
    ],
    id: "znCxQCEp4",
    url: "https://cdn2.thecatapi.com/images/znCxQCEp4.jpg",
    width: 881,
    height: 1280,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "6 - 15",
          metric: "3 - 7",
        },
        id: "birm",
        name: "Birman",
        cfa_url: "http://cfa.org/Breeds/BreedsAB/Birman.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/birman",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/birman",
        temperament: "Affectionate, Active, Gentle, Social",
        origin: "France",
        country_codes: "FR",
        country_code: "FR",
        description:
          "The Birman is a docile, quiet cat who loves people and will follow them from room to room. Expect the Birman to want to be involved in what you’re doing. He communicates in a soft voice, mainly to remind you that perhaps it’s time for dinner or maybe for a nice cuddle on the sofa. He enjoys being held and will relax in your arms like a furry baby.",
        life_span: "14 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "Sacred Birman, Sacred Cat Of Burma",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 2,
        health_issues: 1,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 4,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Birman",
        hypoallergenic: 0,
        reference_image_id: "HOrX5gwLS",
      },
    ],
    id: "9tZCXEYzy",
    url: "https://cdn2.thecatapi.com/images/9tZCXEYzy.jpg",
    width: 1280,
    height: 853,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "6 - 15",
          metric: "3 - 7",
        },
        id: "birm",
        name: "Birman",
        cfa_url: "http://cfa.org/Breeds/BreedsAB/Birman.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/birman",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/birman",
        temperament: "Affectionate, Active, Gentle, Social",
        origin: "France",
        country_codes: "FR",
        country_code: "FR",
        description:
          "The Birman is a docile, quiet cat who loves people and will follow them from room to room. Expect the Birman to want to be involved in what you’re doing. He communicates in a soft voice, mainly to remind you that perhaps it’s time for dinner or maybe for a nice cuddle on the sofa. He enjoys being held and will relax in your arms like a furry baby.",
        life_span: "14 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "Sacred Birman, Sacred Cat Of Burma",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 2,
        health_issues: 1,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 4,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Birman",
        hypoallergenic: 0,
        reference_image_id: "HOrX5gwLS",
      },
    ],
    id: "TKKtEJZVl",
    url: "https://cdn2.thecatapi.com/images/TKKtEJZVl.jpg",
    width: 916,
    height: 1162,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "6 - 15",
          metric: "3 - 7",
        },
        id: "birm",
        name: "Birman",
        cfa_url: "http://cfa.org/Breeds/BreedsAB/Birman.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/birman",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/birman",
        temperament: "Affectionate, Active, Gentle, Social",
        origin: "France",
        country_codes: "FR",
        country_code: "FR",
        description:
          "The Birman is a docile, quiet cat who loves people and will follow them from room to room. Expect the Birman to want to be involved in what you’re doing. He communicates in a soft voice, mainly to remind you that perhaps it’s time for dinner or maybe for a nice cuddle on the sofa. He enjoys being held and will relax in your arms like a furry baby.",
        life_span: "14 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "Sacred Birman, Sacred Cat Of Burma",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 3,
        grooming: 2,
        health_issues: 1,
        intelligence: 3,
        shedding_level: 3,
        social_needs: 4,
        stranger_friendly: 3,
        vocalisation: 1,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Birman",
        hypoallergenic: 0,
        reference_image_id: "HOrX5gwLS",
      },
    ],
    id: "yZE2JpeXz",
    url: "https://cdn2.thecatapi.com/images/yZE2JpeXz.jpg",
    width: 1280,
    height: 720,
  },
];

export const favouriteImagesEntries: Favourite[] = [
  {
    id: 232504658,
    userId: "aciy48",
    imageId: "bu1",
    subId: null,
    createdAt: new Date("2024-12-22T09:10:52.000Z"),
    image: {
      id: "bu1",
      url: "https://cdn2.thecatapi.com/images/bu1.jpg",
    },
  },
  {
    id: 232504659,
    userId: "aciy48",
    imageId: "LIQSvUemz",
    subId: null,
    createdAt: new Date("2024-12-22T09:11:01.000Z"),
    image: {
      id: "LIQSvUemz",
      url: "https://cdn2.thecatapi.com/images/LIQSvUemz.jpg",
    },
  },
  {
    id: 232504759,
    userId: "aciy48",
    imageId: "7l5",
    subId: null,
    createdAt: new Date("2024-12-22T19:33:04.000Z"),
    image: {
      id: "7l5",
      url: "https://cdn2.thecatapi.com/images/7l5.jpg",
    },
  },
  {
    id: 232504760,
    userId: "aciy48",
    imageId: "njaF1fyqI",
    subId: null,
    createdAt: new Date("2024-12-22T19:33:09.000Z"),
    image: {
      id: "njaF1fyqI",
      url: "https://cdn2.thecatapi.com/images/njaF1fyqI.jpg",
    },
  },
  {
    id: 232505761,
    userId: "aciy48",
    imageId: "unPP08xOZ",
    subId: null,
    createdAt: new Date("2024-12-24T11:49:14.000Z"),
    image: {
      id: "unPP08xOZ",
      url: "https://cdn2.thecatapi.com/images/unPP08xOZ.jpg",
    },
  },
  {
    id: 232505788,
    userId: "aciy48",
    imageId: "MjAxMTk1Mw",
    subId: null,
    createdAt: new Date("2024-12-24T12:53:48.000Z"),
    image: {
      id: "MjAxMTk1Mw",
      url: "https://cdn2.thecatapi.com/images/MjAxMTk1Mw.jpg",
    },
  },
  {
    id: 232506900,
    userId: "aciy48",
    imageId: "aai",
    subId: null,
    createdAt: new Date("2024-12-27T13:36:57.000Z"),
    image: {
      id: "aai",
      url: "https://cdn2.thecatapi.com/images/aai.jpg",
    },
  },
  {
    id: 232506901,
    userId: "aciy48",
    imageId: "542",
    subId: null,
    createdAt: new Date("2024-12-27T13:37:01.000Z"),
    image: {
      id: "542",
      url: "https://cdn2.thecatapi.com/images/542.gif",
    },
  },
];
