import type { Image } from "@api/types";

export const catImages: Image[] = [
  {
    breeds: [],
    categories: [
      {
        id: 9,
        name: "dream",
      },
    ],
    id: "6gc",
    url: "https://cdn2.thecatapi.com/images/6gc.jpg",
    width: 500,
    height: 333,
  },
  {
    breeds: [],
    id: "auo",
    url: "https://cdn2.thecatapi.com/images/auo.jpg",
    width: 480,
    height: 360,
  },
  {
    breeds: [],
    id: "bit",
    url: "https://cdn2.thecatapi.com/images/bit.jpg",
    width: 500,
    height: 333,
  },
  {
    breeds: [],
    id: "c0d",
    url: "https://cdn2.thecatapi.com/images/c0d.jpg",
    width: 493,
    height: 700,
  },
  {
    breeds: [],
    id: "d7s",
    url: "https://cdn2.thecatapi.com/images/d7s.jpg",
    width: 324,
    height: 394,
  },
  {
    breeds: [],
    id: "dmo",
    url: "https://cdn2.thecatapi.com/images/dmo.jpg",
    width: 640,
    height: 480,
  },
  {
    breeds: [],
    id: "MTY0NjU4Mg",
    url: "https://cdn2.thecatapi.com/images/MTY0NjU4Mg.jpg",
    width: 1600,
    height: 1200,
  },
  {
    breeds: [],
    id: "MTk0Njc0MQ",
    url: "https://cdn2.thecatapi.com/images/MTk0Njc0MQ.jpg",
    width: 533,
    height: 800,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "5 - 10",
          metric: "2 - 5",
        },
        id: "orie",
        name: "Oriental",
        cfa_url: "http://cfa.org/Breeds/BreedsKthruR/Oriental.aspx",
        vetstreet_url: "http://www.vetstreet.com/cats/oriental",
        vcahospitals_url:
          "https://vcahospitals.com/know-your-pet/cat-breeds/oriental",
        temperament:
          "Energetic, Affectionate, Intelligent, Social, Playful, Curious",
        origin: "United States",
        country_codes: "US",
        country_code: "US",
        description:
          "Orientals are passionate about the people in their lives. They become extremely attached to their humans, so be prepared for a lifetime commitment. When you are not available to entertain her, an Oriental will divert herself by jumping on top of the refrigerator, opening drawers, seeking out new hideaways.",
        life_span: "12 - 14",
        indoor: 0,
        lap: 1,
        alt_names: "Foreign Type",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        dog_friendly: 5,
        energy_level: 5,
        grooming: 1,
        health_issues: 3,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 3,
        vocalisation: 5,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: "https://en.wikipedia.org/wiki/Oriental_Shorthair",
        hypoallergenic: 1,
        reference_image_id: "LutjkZJpH",
      },
    ],
    id: "0eVXT8_lb",
    url: "https://cdn2.thecatapi.com/images/0eVXT8_lb.jpg",
    width: 1396,
    height: 1080,
  },
  {
    breeds: [
      {
        weight: {
          imperial: "7 - 14",
          metric: "3 - 6",
        },
        id: "ebur",
        name: "European Burmese",
        cfa_url: "http://cfa.org/Breeds/BreedsCJ/EuropeanBurmese.aspx",
        temperament: "Sweet, Affectionate, Loyal",
        origin: "Burma",
        country_codes: "MM",
        country_code: "MM",
        description:
          "The European Burmese is a very affectionate, intelligent, and loyal cat. They thrive on companionship and will want to be with you, participating in everything you do. While they might pick a favorite family member, chances are that they will interact with everyone in the home, as well as any visitors that come to call. They are inquisitive and playful, even as adults. ",
        life_span: "10 - 15",
        indoor: 0,
        lap: 1,
        alt_names: "",
        adaptability: 5,
        affection_level: 5,
        child_friendly: 4,
        cat_friendly: 4,
        dog_friendly: 4,
        energy_level: 4,
        grooming: 1,
        health_issues: 4,
        intelligence: 5,
        shedding_level: 3,
        social_needs: 5,
        stranger_friendly: 5,
        vocalisation: 4,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        hypoallergenic: 0,
      },
    ],
    id: "oLtx9gsxx",
    url: "https://cdn2.thecatapi.com/images/oLtx9gsxx.jpg",
    width: 4027,
    height: 2680,
  },
];
